"use client"

import { useState, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { LogOut, Award, BookOpen, TrendingUp, Download, Eye } from "lucide-react"
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
  LineChart,
  Line,
} from "recharts"

// Comprehensive semester data with CSE subjects
const semesterData = [
  {
    semester: 1,
    sgpa: 8.1,
    subjects: [
      { code: "CS101", name: "Programming Fundamentals", credits: 4, midterm: 35, endterm: 42, total: 77, grade: "B+", status: "Pass" },
      { code: "CS102", name: "Computer Architecture", credits: 3, midterm: 38, endterm: 43, total: 81, grade: "A-", status: "Pass" },
      { code: "CS103", name: "Discrete Mathematics", credits: 3, midterm: 32, endterm: 38, total: 70, grade: "B", status: "Pass" },
      { code: "CS104", name: "Data Structures", credits: 4, midterm: 37, endterm: 47, total: 84, grade: "A", status: "Pass" },
      { code: "CS105", name: "Web Development", credits: 3, midterm: 20, endterm: 25, total: 45, grade: "F", status: "Fail" },
    ]
  },
  {
    semester: 2,
    sgpa: 8.35,
    subjects: [
      { code: "CS201", name: "Object-Oriented Programming", credits: 4, midterm: 38, endterm: 44, total: 82, grade: "A-", status: "Pass" },
      { code: "CS202", name: "Database Management Systems", credits: 4, midterm: 36, endterm: 45, total: 81, grade: "A-", status: "Pass" },
      { code: "CS203", name: "Operating Systems", credits: 4, midterm: 35, endterm: 42, total: 77, grade: "B+", status: "Pass" },
      { code: "CS204", name: "Algorithms & Complexity", credits: 3, midterm: 39, endterm: 46, total: 85, grade: "A", status: "Pass" },
      { code: "CS205", name: "Software Engineering", credits: 3, midterm: 37, endterm: 43, total: 80, grade: "A-", status: "Pass" },
    ]
  },
  {
    semester: 3,
    sgpa: 8.42,
    subjects: [
      { code: "CS301", name: "Compiler Design", credits: 4, midterm: 38, endterm: 44, total: 82, grade: "A-", status: "Pass" },
      { code: "CS302", name: "Computer Networks", credits: 4, midterm: 37, endterm: 45, total: 82, grade: "A-", status: "Pass" },
      { code: "CS303", name: "Artificial Intelligence", credits: 3, midterm: 39, endterm: 46, total: 85, grade: "A", status: "Pass" },
      { code: "CS304", name: "Cybersecurity Fundamentals", credits: 3, midterm: 36, endterm: 42, total: 78, grade: "B+", status: "Pass" },
      { code: "CS305", name: "Cloud Computing", credits: 3, midterm: 38, endterm: 44, total: 82, grade: "A-", status: "Pass" },
    ]
  },
  {
    semester: 4,
    sgpa: 8.15,
    subjects: [
      { code: "CS401", name: "Machine Learning", credits: 4, midterm: 35, endterm: 43, total: 78, grade: "B+", status: "Pass" },
      { code: "CS402", name: "Information Retrieval", credits: 3, midterm: 36, endterm: 42, total: 78, grade: "B+", status: "Pass" },
      { code: "CS403", name: "Web Technologies", credits: 4, midterm: 37, endterm: 45, total: 82, grade: "A-", status: "Pass" },
      { code: "CS404", name: "Mobile Application Development", credits: 3, midterm: 33, endterm: 40, total: 73, grade: "B", status: "Pass" },
      { code: "CS405", name: "Advanced Databases", credits: 3, midterm: 34, endterm: 41, total: 75, grade: "B", status: "Pass" },
    ]
  }
]

const performanceData = [
  { semester: "Sem 1", sgpa: 8.1, credits: 17 },
  { semester: "Sem 2", sgpa: 8.35, credits: 18 },
  { semester: "Sem 3", sgpa: 8.42, credits: 17 },
  { semester: "Sem 4", sgpa: 8.15, credits: 17 },
]

export default function Dashboard() {
  const [isLoggedIn, setIsLoggedIn] = useState(false)
  const [expandedSemester, setExpandedSemester] = useState(4)
  const [showProfileModal, setShowProfileModal] = useState(false)
  const [isLoading, setIsLoading] = useState(true)

  useEffect(() => {
    if (typeof window !== "undefined") {
      const loggedIn = localStorage.getItem("isLoggedIn")
      const role = localStorage.getItem("userRole")
      
      if (loggedIn === "true" && role === "student") {
        setIsLoggedIn(true)
        setIsLoading(false)
      } else {
        window.location.href = "/login"
      }
    }
  }, [])

  if (isLoading) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="text-center">
          <p className="text-muted-foreground">Loading...</p>
        </div>
      </div>
    )
  }

  if (!isLoggedIn) {
    return null
  }

  const handleLogout = () => {
    localStorage.removeItem("isLoggedIn")
    localStorage.removeItem("userRole")
    window.location.href = "/"
  }

  const handleExportPDF = () => {
    const reportContent = `
COMPREHENSIVE ACADEMIC REPORT CARD
Generated by VerifyED - Secure Credential Verification Platform

STUDENT INFORMATION
Name: Ayaan Sharma
Student ID: CSE2023-041
Email: ayaan.sharma@example.com
Program: B.Tech in Computer Science & Engineering
Institution: XYZ Institute of Technology
Duration: 2023-2027

CUMULATIVE ACADEMIC PERFORMANCE
Cumulative CGPA: 8.23
Total Credits Completed: 69
Attendance: 87.5%

SEMESTER-WISE BREAKDOWN
${semesterData.map(sem => `
Semester ${sem.semester}
SGPA: ${sem.sgpa}
Subjects Completed: ${sem.subjects.length}
Passed: ${sem.subjects.filter(s => s.status === "Pass").length}
Failed: ${sem.subjects.filter(s => s.status === "Fail").length}
`).join('\n')}

This report is verified and certified by VerifyED.
For authenticity verification, visit www.verified.com
Report Generated: ${new Date().toLocaleDateString()}
    `
    
    const element = document.createElement("a")
    const file = new Blob([reportContent], { type: "text/plain" })
    element.href = URL.createObjectURL(file)
    element.download = `Academic_Report_Ayaan_Sharma_${new Date().getTime()}.txt`
    document.body.appendChild(element)
    element.click()
    document.body.removeChild(element)
  }

  // Calculate cumulative CGPA
  const totalCredits = semesterData.reduce((sum, sem) => {
    return sum + sem.subjects.reduce((semSum, sub) => semSum + sub.credits * (sub.total / 100 * 10), 0)
  }, 0)

  const totalCreditsCount = semesterData.reduce((sum, sem) => {
    return sum + sem.subjects.reduce((semSum, sub) => semSum + sub.credits, 0)
  }, 0)

  const cumulativeCGPA = (totalCredits / totalCreditsCount).toFixed(2)

  // Removed TypeScript type annotation
  const getGradeColor = (status) => {
    if (status === "Fail") return "text-red-400"
    if (status === "Pass") return "text-green-400"
    return "text-foreground"
  }

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b border-border sticky top-0 bg-card/95 backdrop-blur z-40">
        <div className="px-6 py-4 max-w-7xl mx-auto flex justify-between items-center">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 bg-gradient-to-br from-primary to-secondary rounded-lg flex items-center justify-center">
              <Award className="w-5 h-5 text-primary-foreground" />
            </div>
            <span className="font-bold text-xl text-foreground">VerifyED</span>
          </div>
          <div className="flex gap-4">
            <Button onClick={handleExportPDF} variant="outline" size="sm" className="border-border text-foreground hover:bg-muted gap-2 bg-transparent">
              <Download className="w-4 h-4" />
              Export Report
            </Button>
            <Button
              onClick={() => setShowProfileModal(true)}
              variant="outline"
              size="sm"
              className="border-border text-foreground hover:bg-muted gap-2 bg-transparent"
            >
              Profile
            </Button>
            <Button
              onClick={handleLogout}
              variant="outline"
              size="sm"
              className="border-border text-foreground hover:bg-muted gap-2 bg-transparent"
            >
              <LogOut className="w-4 h-4" />
              Logout
            </Button>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="px-6 py-8 max-w-7xl mx-auto">
        {/* Welcome Section */}
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-foreground mb-2">Welcome back, Ayaan Sharma</h1>
          <p className="text-muted-foreground">Student ID: CSE2023-041 | B.Tech CSE (2023-2027)</p>
        </div>

        {/* Profile Card */}
        <Card className="bg-card border-border mb-8 p-6">
          <div className="grid md:grid-cols-3 gap-6">
            <div>
              <p className="text-sm text-muted-foreground mb-1">Program</p>
              <p className="text-foreground font-medium">B.Tech in Computer Science & Engineering</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground mb-1">Institute</p>
              <p className="text-foreground font-medium">XYZ Institute of Technology</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground mb-1">Status</p>
              <Badge className="bg-green-500/20 text-green-400 border-green-500/30">Active Enrollment</Badge>
            </div>
          </div>
        </Card>

        {/* Performance Summary Stats */}
        <div className="grid md:grid-cols-4 gap-4 mb-8">
          <Card className="bg-card border-border p-6">
            <p className="text-sm text-muted-foreground mb-2">Cumulative CGPA</p>
            <p className="text-3xl font-bold text-secondary">{cumulativeCGPA}</p>
            <p className="text-xs text-muted-foreground mt-2">All Semesters</p>
          </Card>

          <Card className="bg-card border-border p-6">
            <p className="text-sm text-muted-foreground mb-2">Current Sem SGPA</p>
            <p className="text-3xl font-bold text-primary">8.15</p>
            <p className="text-xs text-muted-foreground mt-2">Semester 4</p>
          </Card>

          <Card className="bg-card border-border p-6">
            <p className="text-sm text-muted-foreground mb-2">Total Credits</p>
            <p className="text-3xl font-bold text-accent">69</p>
            <p className="text-xs text-muted-foreground mt-2">Completed</p>
          </Card>

          <Card className="bg-card border-border p-6">
            <p className="text-sm text-muted-foreground mb-2">Attendance</p>
            <p className="text-3xl font-bold text-secondary">87.5%</p>
            <p className="text-xs text-muted-foreground mt-2">Academic Year</p>
          </Card>
        </div>

        {/* Performance Chart */}
        <Card className="bg-card border-border p-6 mb-8">
          <h3 className="text-lg font-semibold text-foreground mb-4">SGPA Trend Analysis</h3>
          <ResponsiveContainer width="100%" height={300}>
            <LineChart data={performanceData}>
              <CartesianGrid strokeDasharray="3 3" stroke="oklch(0.2 0 0)" />
              <XAxis dataKey="semester" stroke="oklch(0.65 0 0)" />
              <YAxis stroke="oklch(0.65 0 0)" domain={[7.8, 8.5]} />
              <Tooltip
                contentStyle={{ backgroundColor: "oklch(0.12 0 0)", border: "1px solid oklch(0.2 0 0)" }}
                labelStyle={{ color: "oklch(0.95 0 0)" }}
              />
              <Legend />
              <Line type="monotone" dataKey="sgpa" stroke="oklch(0.45 0.18 250)" strokeWidth={2} dot={{ fill: "oklch(0.45 0.18 250)" }} />
            </LineChart>
          </ResponsiveContainer>
        </Card>

        {/* Semester-wise Report Cards */}
        <div className="space-y-6">
          <h2 className="text-2xl font-bold text-foreground mt-8 mb-6">Detailed Semester Report</h2>

          {semesterData.map((sem) => (
            <Card key={sem.semester} className="bg-card border-border overflow-hidden">
              <div
                className="p-6 cursor-pointer hover:bg-muted/50 transition-colors flex justify-between items-center"
                onClick={() => setExpandedSemester(expandedSemester === sem.semester ? -1 : sem.semester)}
              >
                <div className="flex items-center gap-4">
                  <div className="bg-primary/10 rounded-lg p-3">
                    <BookOpen className="w-6 h-6 text-primary" />
                  </div>
                  <div>
                    <h3 className="text-xl font-bold text-foreground">Semester {sem.semester}</h3>
                    <p className="text-sm text-muted-foreground">SGPA: <span className="text-secondary font-semibold">{sem.sgpa}</span></p>
                  </div>
                </div>
                <Eye className="w-5 h-5 text-muted-foreground" />
              </div>

              {expandedSemester === sem.semester && (
                <div className="border-t border-border px-6 py-6">
                  <div className="overflow-x-auto">
                    <table className="w-full text-sm">
                      <thead>
                        <tr className="border-b border-border">
                          <th className="text-left py-3 text-xs font-semibold text-muted-foreground">Code</th>
                          <th className="text-left py-3 text-xs font-semibold text-muted-foreground">Subject Name</th>
                          <th className="text-center py-3 text-xs font-semibold text-muted-foreground">Credits</th>
                          <th className="text-center py-3 text-xs font-semibold text-muted-foreground">Mid Term</th>
                          <th className="text-center py-3 text-xs font-semibold text-muted-foreground">End Term</th>
                          <th className="text-center py-3 text-xs font-semibold text-muted-foreground">Total</th>
                          <th className="text-center py-3 text-xs font-semibold text-muted-foreground">Grade</th>
                          <th className="text-center py-3 text-xs font-semibold text-muted-foreground">Status</th>
                        </tr>
                      </thead>
                      <tbody>
                        {sem.subjects.map((subject, idx) => (
                          <tr key={idx} className="border-b border-border last:border-b-0 hover:bg-muted/30 transition-colors">
                            <td className="py-4 text-foreground font-medium">{subject.code}</td>
                            <td className="py-4 text-foreground">{subject.name}</td>
                            <td className="py-4 text-center text-foreground">{subject.credits}</td>
                            <td className="py-4 text-center text-foreground">{subject.midterm}</td>
                            <td className="py-4 text-center text-foreground">{subject.endterm}</td>
                            <td className="py-4 text-center font-semibold text-foreground">{subject.total}</td>
                            <td className="py-4 text-center">
                              <Badge
                                className={`${
                                  subject.grade === "A"
                                    ? "bg-green-500/20 text-green-400 border-green-500/30"
                                    : subject.grade === "A-" || subject.grade === "B+"
                                      ? "bg-blue-500/20 text-blue-400 border-blue-500/30"
                                      : subject.grade === "B"
                                        ? "bg-yellow-500/20 text-yellow-400 border-yellow-500/30"
                                        : "bg-red-500/20 text-red-400 border-red-500/30"
                                }`}
                              >
                                {subject.grade}
                              </Badge>
                            </td>
                            <td className={`py-4 text-center font-semibold ${getGradeColor(subject.status)}`}>
                              {subject.status}
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>

                  {/* Semester Summary */}
                  <div className="mt-6 pt-6 border-t border-border">
                    <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                      <div className="bg-background rounded-lg p-4 text-center">
                        <p className="text-xs text-muted-foreground mb-2">Total Credits</p>
                        <p className="text-xl font-bold text-foreground">
                          {sem.subjects.reduce((sum, sub) => sum + sub.credits, 0)}
                        </p>
                      </div>
                      <div className="bg-background rounded-lg p-4 text-center">
                        <p className="text-xs text-muted-foreground mb-2">Semester SGPA</p>
                        <p className="text-xl font-bold text-secondary">{sem.sgpa}</p>
                      </div>
                      <div className="bg-background rounded-lg p-4 text-center">
                        <p className="text-xs text-muted-foreground mb-2">Passed Subjects</p>
                        <p className="text-xl font-bold text-green-400">
                          {sem.subjects.filter(s => s.status === "Pass").length}/{sem.subjects.length}
                        </p>
                      </div>
                      <div className="bg-background rounded-lg p-4 text-center">
                        <p className="text-xs text-muted-foreground mb-2">Failed Subjects</p>
                        <p className="text-xl font-bold text-red-400">
                          {sem.subjects.filter(s => s.status === "Fail").length}/{sem.subjects.length}
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              )}
            </Card>
          ))}
        </div>

        {/* Overall Summary */}
        <Card className="bg-card border-border p-6 mt-8">
          <h3 className="text-lg font-semibold text-foreground mb-6">Overall Academic Summary</h3>
          <div className="grid md:grid-cols-3 gap-8">
            <div className="bg-background rounded-lg p-6 text-center">
              <p className="text-sm text-muted-foreground mb-2">Cumulative CGPA</p>
              <p className="text-4xl font-bold text-secondary">{cumulativeCGPA}</p>
              <p className="text-xs text-muted-foreground mt-3">Out of 4 Semesters</p>
            </div>
            <div className="bg-background rounded-lg p-6 text-center">
              <p className="text-sm text-muted-foreground mb-2">Total Subjects Completed</p>
              <p className="text-4xl font-bold text-primary">{semesterData.reduce((sum, sem) => sum + sem.subjects.length, 0)}</p>
              <p className="text-xs text-muted-foreground mt-3">{semesterData.reduce((sum, sem) => sum + sem.subjects.length - sem.subjects.filter(s => s.status === "Fail").length, 0)} Passed, {semesterData.reduce((sum, sem) => sum + sem.subjects.filter(s => s.status === "Fail").length, 0)} Failed</p>
            </div>
            <div className="bg-background rounded-lg p-6 text-center">
              <p className="text-sm text-muted-foreground mb-2">Average Attendance</p>
              <p className="text-4xl font-bold text-accent">87.5%</p>
              <p className="text-xs text-muted-foreground mt-3">Across All Semesters</p>
            </div>
          </div>
        </Card>

        {/* Verified Credentials */}
        <Card className="bg-card border-border p-6 mt-8">
          <h3 className="text-lg font-semibold text-foreground mb-4">Verified Credentials & Achievements</h3>
          <div className="grid md:grid-cols-3 gap-4">
            {[
              { name: "Data Structures Expert", type: "Certification" },
              { name: "Coding Club Member", type: "Club Badge" },
              { name: "Academic Excellence Award", type: "Achievement" },
            ].map((cred, idx) => (
              <div
                key={idx}
                className="bg-gradient-to-br from-secondary/10 to-accent/10 border border-secondary/30 rounded-lg p-4 text-center"
              >
                <Award className="w-8 h-8 mx-auto mb-3 text-secondary" />
                <h4 className="font-semibold text-foreground mb-1">{cred.name}</h4>
                <p className="text-sm text-muted-foreground">{cred.type}</p>
              </div>
            ))}
          </div>
        </Card>
      </main>

      {/* Profile Modal */}
      {showProfileModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center p-6 z-50">
          <Card className="bg-card border-border max-w-md w-full">
            <div className="p-8">
              <div className="flex justify-between items-start mb-6">
                <h3 className="text-2xl font-bold text-foreground">My Profile</h3>
                <button onClick={() => setShowProfileModal(false)} className="text-muted-foreground hover:text-foreground text-2xl">
                  ×
                </button>
              </div>

              <div className="space-y-4">
                <div className="bg-background rounded-lg p-4">
                  <p className="text-xs text-muted-foreground mb-1">Name</p>
                  <p className="text-foreground font-semibold">Ayaan Sharma</p>
                </div>

                <div className="bg-background rounded-lg p-4">
                  <p className="text-xs text-muted-foreground mb-1">Student ID</p>
                  <p className="text-foreground font-semibold">CSE2023-041</p>
                </div>

                <div className="bg-background rounded-lg p-4">
                  <p className="text-xs text-muted-foreground mb-1">Email</p>
                  <p className="text-foreground font-semibold">ayaan.sharma@example.com</p>
                </div>

                <div className="bg-background rounded-lg p-4">
                  <p className="text-xs text-muted-foreground mb-1">Program</p>
                  <p className="text-foreground font-semibold">B.Tech CSE (2023-2027)</p>
                </div>

                <div className="bg-background rounded-lg p-4">
                  <p className="text-xs text-muted-foreground mb-1">Cumulative CGPA</p>
                  <p className="text-foreground font-semibold">{cumulativeCGPA}</p>
                </div>

                <div className="bg-background rounded-lg p-4">
                  <p className="text-xs text-muted-foreground mb-1">Verification Status</p>
                  <Badge className="bg-green-500/20 text-green-400 border-green-500/30">Verified & Certified</Badge>
                </div>
              </div>

              <div className="mt-8 flex gap-3">
                <Button onClick={handleExportPDF} className="flex-1 bg-secondary hover:bg-secondary/90 gap-2">
                  <Download className="w-4 h-4" />
                  Export
                </Button>
                <Button onClick={() => setShowProfileModal(false)} variant="outline" className="flex-1 border-border bg-transparent">
                  Close
                </Button>
              </div>
            </div>
          </Card>
        </div>
      )}
    </div>
  )
}